// examples/appkit-core/vue/vue-ak-basic-up/src/components/ActionButton.vue
<template>
  <div v-if="provider" class="appkit-buttons-container">
    <template v-if="session">
      <button @click="disconnect">Disconnect</button>
      <button @click="getBalance">Get Balance</button>
    </template>
    <button v-else @click="connect">Connect</button>
  </div>
</template>

<script setup lang="ts">
import type { UniversalProvider } from '@walletconnect/universal-provider'

interface Props {
  provider?: InstanceType<typeof UniversalProvider>
  session: unknown
  account?: string
  onSessionChange: (session: unknown) => void
  onBalanceChange: (balance: string | undefined) => void
  onAccountChange: (account: string | undefined) => void
  onNetworkChange: (network: string | undefined) => void
}

const props = defineProps<Props>()

const disconnect = async () => {
  if (!props.provider) return
  await props.provider.disconnect()
  props.onSessionChange(props.provider.session)
  props.onBalanceChange(undefined)
  props.onAccountChange(undefined)
  props.onNetworkChange(undefined)
}

const getBalance = async () => {
  if (!props.provider || !props.account) return
  const balance = await props.provider.request({
    method: 'eth_getBalance',
    params: [props.account, 'latest']
  })
  props.onBalanceChange(balance as string)
}

const connect = async () => {
  if (!props.provider) return
  await props.provider.connect({
    optionalNamespaces: {
      eip155: {
        methods: [
          'eth_sendTransaction',
          'eth_signTransaction',
          'eth_sign',
          'personal_sign',
          'eth_signTypedData'
        ],
        chains: ['eip155:1'],
        events: ['chainChanged', 'accountsChanged']
      }
    }
  })
}
</script>

// examples/next-ak-basic-up-app-router/src/app/components/ActionButton.tsx
import UniversalProvider from '@walletconnect/universal-provider'

interface ActionButtonListProps {
  provider: UniversalProvider
  session: unknown
  account?: string
  onSessionChange: (session: unknown) => void
  onAccountChange: (account: string | undefined) => void
  onBalanceChange: (balance: string | undefined) => void
  onNetworkChange: (network: string | undefined) => void
}

export default function ActionButtonList({
  provider,
  session,
  account,
  onSessionChange,
  onAccountChange,
  onBalanceChange,
  onNetworkChange
}: ActionButtonListProps) {
  return (
    <div className="appkit-buttons-container">
      {session ? (
        <>
          <button
            onClick={async () => {
              await provider.disconnect()
              onSessionChange(provider.session)
              onBalanceChange(undefined)
              onAccountChange(undefined)
              onNetworkChange(undefined)
            }}
          >
            Disconnect
          </button>
          <button
            onClick={async () => {
              console.log(account)
              console.log(provider)

              const requestArguments = {
                method: 'eth_getBalance',
                params: [account, 'latest']
              }
              const balance = await provider.request(requestArguments, 'eip155:1')

              console.log(balance)

              onBalanceChange(balance as string)
            }}
          >
            Get Balance
          </button>
        </>
      ) : (
        <button
          onClick={async () =>
            await await provider.connect({
              optionalNamespaces: {
                eip155: {
                  methods: [
                    'eth_sendTransaction',
                    'eth_signTransaction',
                    'eth_sign',
                    'personal_sign',
                    'eth_signTypedData'
                  ],
                  chains: ['eip155:1'],
                  events: ['chainChanged', 'accountsChanged']
                }
              }
            })
          }
        >
          Connect
        </button>
      )}
    </div>
  )
}
