// examples/react-adi-custom-network/src/App.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { WagmiProvider } from 'wagmi'

import ActionButtonList from './components/ActionButton'
import Footer from './components/Footer'
import InfoList from './components/InfoList'
import { useAppKitTheme, wagmiAdapter } from './config'

const queryClient = new QueryClient()

export default function App() {
  const { themeMode } = useAppKitTheme()
  document.documentElement.className = themeMode

  return (
    <WagmiProvider config={wagmiAdapter.wagmiConfig}>
      <QueryClientProvider client={queryClient}>
        <div className="page-container">
          <div className="logo-container">
            <img
              src={themeMode === 'dark' ? '/reown-logo-white.png' : '/reown-logo.png'}
              alt="Reown"
              width="150"
            />
            <img src="/appkit-logo.png" alt="Reown" width="150" />
          </div>

          <h1 className="page-title">React ADI Custom Network Example</h1>

          <div className="appkit-buttons-container">
            <appkit-button />
            <appkit-network-button />
          </div>

          <ActionButtonList />
          <InfoList />
          <Footer />
        </div>
      </QueryClientProvider>
    </WagmiProvider>
  )
}

// examples/vue-wagmi-solana/src/App.vue
<template>
  <div class="page-container">
    <div class="logo-container">
      <img
        :src="themeState.themeMode === 'dark' ? '/reown-logo-white.png' : '/reown-logo.png'"
        alt="Reown"
        width="150"
      />
      <img src="/appkit-logo.png" alt="Reown" width="150" />
    </div>

    <h1 class="page-title">Vue Wagmi + Solana Example</h1>

    <div class="appkit-buttons-container">
      <appkit-button />
      <appkit-network-button />
    </div>

    <ActionButtonList />

    <InfoList />

    <Footer />
  </div>
</template>

<script>
import { useAppKitTheme } from '@reown/appkit/vue'

import ActionButtonList from './components/ActionButton.vue'
import Footer from './components/Footer.vue'
import InfoList from './components/InfoList.vue'

export default {
  name: 'App',
  components: {
    ActionButtonList,
    InfoList,
    Footer
  },
  setup() {
    const themeState = useAppKitTheme()
    document.documentElement.className = themeState.themeMode
    return {
      themeState
    }
  }
}
</script>
