// packages/solid/src/utils/useAsyncHookBuilder.ts
import { createEffect, createSignal } from 'solid-js'

export function useAsyncHookBuilder<TArgs, TResult>(
  fetcher: (opts: TArgs) => Promise<TResult>,
  initialOpts?: TArgs
) {
  const [isLoading, setIsLoading] = createSignal<boolean>(false)
  const [error, setError] = createSignal<unknown>(null)
  const [data, setData] = createSignal<TResult | null>(null)
  const [fetchedInitial, setFetchedInitial] = createSignal<boolean>(false)

  async function refetch(opts: TArgs) {
    try {
      setIsLoading(true)
      const fetchedData = await fetcher(opts)
      setData(() => fetchedData)
    } catch (err: unknown) {
      setError(err)
    } finally {
      setIsLoading(false)
    }
  }

  createEffect(() => {
    if (initialOpts && !fetchedInitial())
      refetch(initialOpts).then(() => {
        setFetchedInitial(true)
      })
  })

  return {
    data,
    refetch,
    isLoading,
    error
  }
}

// packages/react/src/utils/useAsyncHookBuilder.ts
import { useCallback, useEffect, useState } from 'react'

export function useAsyncHookBuilder<TArgs, TResult>(
  fetcher: (opts: TArgs) => Promise<TResult>,
  initialOpts?: TArgs
) {
  const [isLoading, setIsLoading] = useState<boolean>(false)
  const [error, setError] = useState<unknown>(null)
  const [data, setData] = useState<TResult | null>(null)
  const [fetchedInitial, setFetchedInitial] = useState<boolean>(false)

  const refetch = useCallback(
    async (opts: TArgs) => {
      try {
        setIsLoading(true)
        const fetchedData = await fetcher(opts)
        setData(fetchedData)
      } catch (err: unknown) {
        setError(err)
      } finally {
        setIsLoading(false)
      }
    },
    [fetcher, setError, setIsLoading, setData]
  )

  useEffect(() => {
    if (initialOpts && !fetchedInitial)
      refetch(initialOpts).then(() => {
        setFetchedInitial(true)
      })
  }, [initialOpts, refetch, setFetchedInitial, fetchedInitial])

  return {
    data,
    refetch,
    isLoading,
    error
  }
}
