// packages/react/src/components/Web3Modal.tsx
import type { ConfigOptions } from '@web3modal/core'
import { ClientCtrl, ConfigCtrl } from '@web3modal/core'
import React, { useCallback, useEffect } from 'react'
import { Modal } from './Modal'

/**
 * Props
 */
interface Props {
  config: ConfigOptions
}

/**
 * Component
 */
export function Web3Modal({ config }: Props) {
  const onConfigure = useCallback(async () => {
    ConfigCtrl.setConfig(config)
    await ClientCtrl.setSolanaClient({ projectId: config.projectId })
    if (config.ethereum) await ClientCtrl.setEthereumClient(config.ethereum)
    await import('@web3modal/ui')
  }, [config])

  useEffect(() => {
    onConfigure()
  }, [onConfigure])

  return <Modal />
}

// packages/solidjs/src/components/Web3Modal.tsx
import type { ConfigOptions } from '@web3modal/core'
import { ClientCtrl, ConfigCtrl } from '@web3modal/core'
import { createEffect } from 'solid-js'
import { Modal } from './Modal'

/**
 * Props
 */
interface Props {
  config: ConfigOptions
}

/**
 * Component
 */
export function Web3Modal(props: Props) {
  async function onConfigure() {
    ConfigCtrl.setConfig(props.config)
    if (props.config.ethereum) await ClientCtrl.setEthereumClient(props.config.ethereum)
    await import('@web3modal/ui')
  }

  createEffect(() => {
    onConfigure()
  })

  return <Modal />
}
