// packages/solidjs/src/hooks/data/useClientInitialized.ts
import { ClientCtrl } from '@web3modal/core'
import { createSignal, onCleanup } from 'solid-js'

export function useClientInitialized() {
  const [initialized, setInitialized] = createSignal(ClientCtrl.state.initialized)

  const unsubscribe = ClientCtrl.subscribe(newClient => setInitialized(newClient.initialized))
  onCleanup(() => unsubscribe())

  return initialized
}

// packages/react/src/hooks/data/useClientInitialized.ts
import { ClientCtrl } from '@web3modal/core'
import { useEffect, useState } from 'react'

export function useClientInitialized() {
  const [initialized, setInitialized] = useState(ClientCtrl.state.initialized)

  useEffect(() => {
    const unsubscribe = ClientCtrl.subscribe(newClient => setInitialized(newClient.initialized))

    return () => unsubscribe()
  }, [])

  return initialized
}
