// packages/react/src/Web3ModalProvider.tsx
import type { ConfigOptions } from '@web3modal/core'
import { Web3ModalCore } from '@web3modal/core'
import type { ReactNode } from 'react'
import React, { useEffect } from 'react'
import { Web3Modal as Modal } from './Web3Modal'

/**
 * Props
 */
interface Props {
  children: ReactNode | ReactNode[]
  config: ConfigOptions
}

/**
 * Component
 */
export function Web3ModalProvider({ children, config }: Props) {
  async function onConfigure() {
    Web3ModalCore.configure(config)
    await import('@web3modal/ui')
  }

  useEffect(() => {
    onConfigure()
  }, [])

  return (
    <>
      {children}
      <Modal />
    </>
  )
}

// packages/solid/src/components/Web3ModalProvider.tsx
import type { ConfigOptions } from '@web3modal/core'
import { ClientCtrl, ConfigCtrl } from '@web3modal/core'
import type { ReactNode } from 'react'
import { createEffect } from 'solid-js'
import { Web3Modal as Modal } from './Web3Modal'

/**
 * Props
 */
interface Props {
  children: ReactNode | ReactNode[]
  config: ConfigOptions
}

/**
 * Component
 */
export function Web3ModalProvider(props: Props) {
  async function onConfigure() {
    ConfigCtrl.setConfig(props.config)
    if (props.config.ethereum) await ClientCtrl.setEthereumClient(props.config.ethereum)
    await import('@web3modal/ui')
  }

  createEffect(() => {
    onConfigure()
  })

  return (
    <>
      {props.children}
      <Modal />
    </>
  )
}
