// examples/appkit-core/vue/vue-ak-basic-sign-client/src/components/InfoList.vue
<template>
  <div class="code-container-wrapper">
    <section class="code-container">
      <h2 class="code-container-title">Account</h2>
      <div class="code-container-content">
        <pre>{{ JSON.stringify(account, null, 2) }}</pre>
      </div>
    </section>

    <section class="code-container">
      <h2 class="code-container-title">Network</h2>
      <div class="code-container-content">
        <pre>{{ JSON.stringify(network, null, 2) }}</pre>
      </div>
    </section>

    <section class="code-container">
      <h2 class="code-container-title">Session</h2>
      <div class="code-container-content">
        <pre>{{ JSON.stringify(session, null, 2) }}</pre>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
interface Props {
  account?: string
  network?: string
  session: unknown
}

defineProps<Props>()
</script>

// examples/appkit-core/next/next-ak-basic-sign-client-app-router/src/app/components/InfoList.tsx
interface InfoListProps {
  account?: string
  network?: string
  session: any
}

export default function InfoList({ account, network, session }: InfoListProps) {
  return (
    <div className="code-container-wrapper">
      <section className="code-container">
        <h2 className="code-container-title">Account</h2>
        <div className="code-container-content">
          <pre>{JSON.stringify(account, null, 2)}</pre>
        </div>
      </section>

      <section className="code-container">
        <h2 className="code-container-title">Network</h2>
        <div className="code-container-content">
          <pre>{JSON.stringify(network, null, 2)}</pre>
        </div>
      </section>

      <section className="code-container">
        <h2 className="code-container-title">Session</h2>
        <div className="code-container-content">
          {session && <pre>{JSON.stringify(session, null, 2)}</pre>}
        </div>
      </section>
    </div>
  )
}
