// examples/vue-ep/src/components/ActionButton.vue
<template>
  <div v-if="provider" class="appkit-buttons-container">
    <template v-if="session">
      <button @click="disconnect">Disconnect</button>
      <button @click="getBalance">Get Balance</button>
    </template>
    <button v-else @click="connect">Connect</button>
  </div>
</template>

<script setup lang="ts">
import type { EthereumProvider } from '@walletconnect/ethereum-provider'

interface Props {
  provider?: InstanceType<typeof EthereumProvider>
  session: unknown
  account?: string
  onSessionChange: (session: unknown) => void
  onBalanceChange: (balance: string | undefined) => void
  onAccountChange: (account: string | undefined) => void
  onNetworkChange: (network: string | undefined) => void
}

const props = defineProps<Props>()

const disconnect = async () => {
  if (!props.provider) return
  await props.provider.disconnect()
  props.onSessionChange(props.provider.session)
  props.onBalanceChange(undefined)
  props.onAccountChange(undefined)
  props.onNetworkChange(undefined)
}

const getBalance = async () => {
  if (!props.provider || !props.account) return
  const balance = await props.provider.request({
    method: 'eth_getBalance',
    params: [props.account, 'latest']
  })
  props.onBalanceChange(balance as string)
}

const connect = async () => {
  if (!props.provider) return
  await props.provider.connect()
}
</script>

// examples/react-ep/src/components/ActionButton.tsx
import type { EthereumProvider } from '@walletconnect/ethereum-provider'

interface ActionButtonListProps {
  provider?: InstanceType<typeof EthereumProvider>
  session: unknown
  account?: string
  onSessionChange: (session: unknown) => void
  onBalanceChange: (balance: string | undefined) => void
  onAccountChange: (account: string | undefined) => void
  onNetworkChange: (network: string | undefined) => void
}

export default function ActionButtonList({
  provider,
  session,
  account,
  onSessionChange,
  onBalanceChange,
  onAccountChange,
  onNetworkChange
}: ActionButtonListProps) {
  if (!provider) return null

  return (
    <div className="appkit-buttons-container">
      {session ? (
        <>
          <button
            onClick={async () => {
              await provider.disconnect()
              onSessionChange(provider.session)
              onBalanceChange(undefined)
              onAccountChange(undefined)
              onNetworkChange(undefined)
            }}
          >
            Disconnect
          </button>
          <button
            onClick={async () => {
              const balance = await provider.request({
                method: 'eth_getBalance',
                params: [account, 'latest']
              })
              onBalanceChange(balance as string)
            }}
          >
            Get Balance
          </button>
        </>
      ) : (
        <button onClick={async () => await provider.connect()}>Connect</button>
      )}
    </div>
  )
}
