// packages/solid/src/utils/useAsyncHookBuilder.ts
import { createEffect, createSignal } from 'solid-js'

export function useAsyncHookBuilder<TArgs, TResult>(
  fetcher: (opts: TArgs) => Promise<TResult>,
  initialOpts?: TArgs
) {
  const [isLoading, setIsLoading] = createSignal<boolean>(false)
  const [error, setError] = createSignal<unknown>(null)
  const [data, setData] = createSignal<TResult | null>(null)
  const [fetchedInitial, setFetchedInitial] = createSignal<boolean>(false)

  async function refetch(opts: TArgs) {
    try {
      setIsLoading(true)
      const fetchedData = await fetcher(opts)
      setData(() => fetchedData)
    } catch (err: unknown) {
      setError(err)
    } finally {
      setIsLoading(false)
    }
  }

  createEffect(() => {
    if (initialOpts && !fetchedInitial())
      refetch(initialOpts).then(() => {
        setFetchedInitial(true)
      })
  })

  return {
    data,
    refetch,
    isLoading,
    error
  }
}

// packages/react/src/hooks/utils/useAsyncHookBuilder.ts
import { useCallback, useEffect, useState } from 'react'

export function useAsyncHookBuilder<TArgs, TResult>(
  action: (args: TArgs) => Promise<TResult>,
  initialArgs: TArgs
) {
  const [data, setData] = useState<TResult | undefined>(undefined)
  const [error, setError] = useState<Error | undefined>(undefined)
  const [isLoading, setIsLoading] = useState(false)

  const onAction = useCallback(
    async (args: TArgs) => {
      try {
        setIsLoading(true)
        const actionData = await action(args)
        setData(actionData)
        setError(undefined)
      } catch (err: unknown) {
        if (err instanceof Error) setError(err)
        else setError(new Error('Unknown error'))
      } finally {
        setIsLoading(false)
      }
    },
    [action]
  )

  useEffect(() => {
    onAction(initialArgs)
  }, [])

  return {
    data,
    error,
    onAction,
    isLoading
  }
}
