// packages/solidjs/src/hooks/utils/useOptionsChange.ts
import { createEffect, createSignal } from 'solid-js'

export function useOptionsChange<TOptions>(callback: () => void, options?: TOptions) {
  const newOptions = typeof options === 'object' ? JSON.stringify(options) : undefined
  const [prevOptions, setPrevOptions] = createSignal(newOptions)

  createEffect(() => {
    if (newOptions && prevOptions() && newOptions !== prevOptions()) callback()
    setPrevOptions(newOptions)
  })
}

// packages/react/src/hooks/utils/useOptionsChange.ts
import { useEffect, useState } from 'react'

export function useOptionsChange<TOptions>(callback: () => void, options?: TOptions) {
  const newOptions = typeof options === 'object' ? JSON.stringify(options) : undefined
  const [prevOptions, setPrevOptions] = useState(newOptions)

  useEffect(() => {
    if (newOptions && prevOptions && newOptions !== prevOptions) callback()
    setPrevOptions(newOptions)
  }, [newOptions, prevOptions, callback])
}
