// packages/solid/src/hooks/account/useAccount.ts
import type { Account } from '@web3modal/core'
import { AccountCtrl, initialAccountlState } from '@web3modal/core'
import { createEffect, createSignal } from 'solid-js'

export function useAccount() {
  const [account, setAccount] = createSignal<Account>(initialAccountlState)

  createEffect(() => {
    setAccount(AccountCtrl.state)
    const unsubscribe = AccountCtrl.subscribe(newAccount => setAccount({ ...newAccount }))

    return () => unsubscribe()
  })

  return account
}

// packages/react/src/hooks/useAccount.ts
import type { Account } from '@web3modal/core'
import { AccountCtrl, initialAccountlState } from '@web3modal/core'
import { useEffect, useState } from 'react'

export function useAccount() {
  const [account, setAccount] = useState<Account>(initialAccountlState)

  useEffect(() => {
    const unsubscribe = AccountCtrl.subscribe(newAccount => setAccount({ ...newAccount }))

    return () => unsubscribe()
  }, [])

  return account
}
